# Install dependencies only when needed
FROM apitable/nodepy:16.15.0-alpine AS deps

RUN npm install -g pnpm@8.13.1 --registry=https://registry.npmmirror.com

WORKDIR /workspace-install

COPY ./pnpm-workspace.yaml ./package.json ./pnpm-lock.yaml ./.npmrc ./
COPY ./patches/ ./patches

# datasheet dependencies packages
COPY frontend/components/package.json ./frontend/components/
COPY packages/core/package.json ./packages/core/
COPY packages/i18n-lang/package.json ./packages/i18n-lang/
COPY frontend/icons/package.json ./frontend/icons/
COPY frontend/widget-sdk/package.json ./frontend/widget-sdk/

# datasheet main
COPY frontend/datasheet/package.json ./frontend/datasheet/

RUN pnpm install

# stage builder
FROM apitable/nodepy:16.15.0-alpine AS builder

ARG SEMVER_FULL="v0.0.0-alpha"
ARG NEXT_ASSET_PREFIX=""
ARG NEXT_PUBLIC_ASSET_PREFIX=""
ENV SEMVER_FULL=${SEMVER_FULL}

RUN npm install -g pnpm@8.13.1 --registry=https://registry.npmmirror.com

WORKDIR /app

COPY ./pnpm-workspace.yaml ./package.json ./pnpm-lock.yaml ./nx.json ./common-tsconfig.json ./tsconfig.json ./.eslintrc ./
COPY packages/ ./packages/
COPY frontend/ ./frontend/

COPY --from=deps /workspace-install/patches ./patches
COPY --from=deps /workspace-install/node_modules ./node_modules
COPY --from=deps /workspace-install/frontend/datasheet/node_modules ./frontend/datasheet/node_modules
COPY --from=deps /workspace-install/frontend/components/node_modules ./frontend/components/node_modules
COPY --from=deps /workspace-install/packages/core/node_modules ./packages/core/node_modules
COPY --from=deps /workspace-install/frontend/icons/node_modules ./frontend/icons/node_modules
COPY --from=deps /workspace-install/packages/i18n-lang/node_modules ./packages/i18n-lang/node_modules
COPY --from=deps /workspace-install/frontend/widget-sdk/node_modules ./frontend/widget-sdk/node_modules

RUN set -eux; \
    sed -i~ '$a\WEB_CLIENT_VERSION='${SEMVER_FULL}'' frontend/datasheet/.env; \
    sed -i~ 's~^NEXT_ASSET_PREFIX=.*~NEXT_ASSET_PREFIX='${NEXT_ASSET_PREFIX}'~' frontend/datasheet/.env; \
    sed -i~ 's~^NEXT_PUBLIC_ASSET_PREFIX=.*~NEXT_PUBLIC_ASSET_PREFIX='${NEXT_PUBLIC_ASSET_PREFIX}'~' frontend/datasheet/.env

RUN pnpm --version

RUN pnpm run build:dst

# stage runner
FROM apitable/nodepy:16.15.0-alpine AS runner

WORKDIR /app

ENV NODE_ENV production

# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/pnpm-workspace.yaml /app/package.json /app/pnpm-lock.yaml ./
COPY --from=builder /app/frontend/datasheet/public ./frontend/datasheet/public
COPY --from=builder /app/frontend/datasheet/next.config.js \
                    /app/frontend/datasheet/package.json \
                    ./frontend/datasheet/

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/frontend/datasheet/web_build/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/frontend/datasheet/web_build/static ./frontend/datasheet/web_build/static

WORKDIR /app/frontend/datasheet

USER nextjs

EXPOSE 8080

ENV PORT 8080

CMD [ "node", "server.js" ]
