plugins {
    id "checkstyle"
}

defaultTasks("build")

allprojects {
    group = "com.apitable"

    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
    }
}

def checkstyleVersion = libs.versions.checkstyle.get()

subprojects {
    apply plugin: 'checkstyle'

    checkstyle {
        toolVersion = checkstyleVersion
        ignoreFailures = false
        maxWarnings = 0
    }

    configurations.configureEach {
        resolutionStrategy {
            cacheChangingModulesFor 0, 'seconds'
        }
    }
}